export { redactSecrets } from './redact'
export { getStorageEstimate } from './storage-estimate'
export type { StorageEstimateResult } from './storage-estimate'
export { copyText } from './clipboard'
export { getBuildInfo } from './build-info'
export type { BuildInfo } from './build-info'
export { createIndexedDbErrorLog, ERROR_LOG_CAP } from './error-log'
export type { ErrorLog, LogEntry, NewLogEntry, ErrorLogDeps } from './error-log'
export { installErrorCapture } from './error-capture'
export type { CaptureTarget } from './error-capture'
export { withAdapterErrorLogging } from './adapter-error-logging'
export { collectDiagnostics, formatDiagnosticsReport } from './diagnostics-report'
export type { DiagnosticsSnapshot, CollectDiagnosticsDeps } from './diagnostics-report'
