#!/usr/bin/env node
/**
 * The restore drill (T054) — the actual deliverable. A backup nobody has
 * restored is a guess, not a backup. Restores a `backup.mjs` dump into a
 * SCRATCH database and verifies it, so "can we actually get her phrases
 * back" is answered by running code, not by trusting that `pg_dump` didn't
 * silently fail three months ago.
 *
 * Structurally impossible to hit production: the target database name is
 * generated by this script (`scratchDatabaseName`, `SCRATCH_DATABASE_PREFIX`
 * + random suffix) and takes no input from argv, env, or the backup file —
 * there is no code path from a caller-supplied value to the database this
 * restores into. `DATABASE_URL` supplies only host/port/user/password (its
 * own database name is read and then discarded, never used).
 *
 * Usage:
 *   node scripts/restore-drill.mjs <backup-file.sql.gz> \
 *     [--library-key=<key>] [--expect-sha256=<hex>]
 *
 * `--library-key`/`--expect-sha256` are optional: without them the drill
 * only proves the schema restores (users/sessions/libraries tables exist).
 * With them, it also proves one library's `data` round-trips byte-identical
 * — compute the hash before backing up (`sha256sum` on the row, or ask
 * `backup.mjs`'s caller to capture it) and pass it in here after restore.
 *
 * Exits 0 only if every check passes; exits 1 and prints which check failed
 * otherwise. Always drops the scratch database on the way out, pass or fail.
 *
 * Requires `psql` on PATH (same host as `backup.mjs`'s `pg_dump`) and the
 * `pg` npm package (already a dependency of this repo).
 */
import { spawn } from 'node:child_process'
import { createReadStream } from 'node:fs'
import { createGunzip } from 'node:zlib'
import { createHash, randomBytes } from 'node:crypto'
import pg from 'pg'
import { createLogger } from '../server/logger.js'
import { parsePgUrl, sanitizedUriWithDatabase, uriWithDatabase } from './pg-url.mjs'

const { Pool } = pg

export const SCRATCH_DATABASE_PREFIX = 'phrase_drill_restore_drill_'

/** Takes no arguments, deliberately — see the module comment above. */
export function scratchDatabaseName() {
  return `${SCRATCH_DATABASE_PREFIX}${randomBytes(8).toString('hex')}`
}

const KNOWN_FLAGS = new Set(['--library-key', '--expect-sha256'])

export function parseRestoreArgs(argv) {
  const positional = []
  const flags = {}
  for (const arg of argv) {
    if (arg.startsWith('--')) {
      const eq = arg.indexOf('=')
      const key = eq === -1 ? arg : arg.slice(0, eq)
      if (!KNOWN_FLAGS.has(key)) throw new Error(`unrecognized flag: ${key}`)
      flags[key] = eq === -1 ? '' : arg.slice(eq + 1)
    } else {
      positional.push(arg)
    }
  }
  if (positional.length === 0) throw new Error('a backup file is required, e.g. node scripts/restore-drill.mjs ./phrase-drill-....sql.gz')
  return {
    backupFile: positional[0],
    libraryKey: flags['--library-key'] ?? null,
    expectSha256: flags['--expect-sha256'] ?? null,
  }
}

function run(command, args, { env, stdinStream } = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { env: env ?? process.env, stdio: [stdinStream ? 'pipe' : 'ignore', 'ignore', 'pipe'] })
    let stderr = ''
    child.stderr.on('data', (c) => {
      stderr += c.toString()
    })
    child.on('error', reject)
    child.on('close', (code) => (code === 0 ? resolve() : reject(new Error(`${command} exited ${code}: ${stderr.trim()}`))))
    if (stdinStream) {
      stdinStream.pipe(child.stdin)
      stdinStream.on('error', reject)
    }
  })
}

async function restoreInto({ databaseUrl, scratchName, backupFile, password }) {
  const scratchUri = sanitizedUriWithDatabase(databaseUrl, scratchName)
  const decompressed = createReadStream(backupFile).pipe(createGunzip())
  await run('psql', [scratchUri, '-v', 'ON_ERROR_STOP=1', '-f', '-'], {
    env: { ...process.env, PGPASSWORD: password },
    stdinStream: decompressed,
  })
}

async function verify({ pool, libraryKey, expectSha256 }) {
  const checks = []

  const { rows: tableRows } = await pool.query(
    `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name = ANY($1)`,
    [['users', 'sessions', 'libraries']],
  )
  const found = new Set(tableRows.map((r) => r.table_name))
  for (const table of ['users', 'sessions', 'libraries']) {
    checks.push({ name: `table "${table}" exists`, pass: found.has(table) })
  }

  if (libraryKey) {
    const { rows } = await pool.query('SELECT data FROM libraries WHERE library_key = $1', [libraryKey])
    const row = rows[0]
    checks.push({ name: `library "${libraryKey}" round-trips`, pass: Boolean(row) })
    if (row) {
      const actualSha256 = createHash('sha256').update(row.data).digest('hex')
      if (expectSha256) {
        checks.push({ name: 'restored data is byte-identical to the pre-backup hash', pass: actualSha256 === expectSha256, detail: actualSha256 })
      } else {
        checks.push({ name: 'restored data sha256 (no --expect-sha256 given to compare against)', pass: true, detail: actualSha256 })
      }
    }
  }

  return checks
}

export async function main(argv = process.argv.slice(2)) {
  const { backupFile, libraryKey, expectSha256 } = parseRestoreArgs(argv)

  const databaseUrl = process.env.DATABASE_URL
  if (!databaseUrl) throw new Error('DATABASE_URL is required (host/port/user/password of the Postgres server to restore into)')

  const { password } = parsePgUrl(databaseUrl)
  const logger = createLogger({ secrets: [password].filter(Boolean) })

  const scratchName = scratchDatabaseName()
  if (!scratchName.startsWith(SCRATCH_DATABASE_PREFIX)) {
    // unreachable given scratchDatabaseName's implementation, but this is
    // exactly the assertion that makes "structurally impossible" true
    // rather than merely likely — refuse rather than trust the format.
    throw new Error('refusing to restore: scratch database name does not carry the expected prefix')
  }

  // in-process `pg` connections keep the password embedded in the URI
  // (uriWithDatabase) — never passed to a child process, so there is no
  // argv-exposure concern the way there is for pg_dump/psql below.
  const maintenancePool = new Pool({ connectionString: uriWithDatabase(databaseUrl, 'postgres') })

  let pool
  try {
    logger.info('restore-drill: creating scratch database', { scratchName })
    await maintenancePool.query(`CREATE DATABASE "${scratchName}"`)

    logger.info('restore-drill: restoring', { backupFile, scratchName })
    await restoreInto({ databaseUrl, scratchName, backupFile, password })

    pool = new Pool({ connectionString: uriWithDatabase(databaseUrl, scratchName) })
    const checks = await verify({ pool, libraryKey, expectSha256 })

    for (const check of checks) {
      const line = `${check.pass ? 'PASS' : 'FAIL'} — ${check.name}${check.detail ? ` (${check.detail})` : ''}`
      console.log(line)
    }

    const failed = checks.filter((c) => !c.pass)
    if (failed.length > 0) {
      logger.error('restore-drill: failed', { failedChecks: failed.map((c) => c.name) })
      process.exitCode = 1
    } else {
      logger.info('restore-drill: all checks passed', { count: checks.length })
    }
  } catch (err) {
    logger.error('restore-drill: failed', { error: err instanceof Error ? err.message : String(err) })
    process.exitCode = 1
  } finally {
    if (pool) await pool.end().catch(() => {})
    logger.info('restore-drill: dropping scratch database', { scratchName })
    await maintenancePool.query(`DROP DATABASE IF EXISTS "${scratchName}" WITH (FORCE)`).catch(async () => {
      // WITH (FORCE) needs Postgres 13+; fall back for anything older.
      await maintenancePool.query(`DROP DATABASE IF EXISTS "${scratchName}"`).catch(() => {})
    })
    await maintenancePool.end().catch(() => {})
  }
}

const isMain = process.argv[1] && import.meta.url === new URL(process.argv[1], 'file:').href
if (isMain) {
  main().catch(() => {
    process.exitCode = 1
  })
}
