#!/usr/bin/env node
/**
 * The restore drill (T054) — the actual deliverable. A backup nobody has
 * restored is a guess, not a backup. Restores a `backup.mjs` dump into a
 * SCRATCH database and verifies it, so "can we actually get her phrases
 * back" is answered by running code, not by trusting that `pg_dump` didn't
 * silently fail three months ago.
 *
 * Structurally impossible to hit production: the target database name is
 * generated by this script (`scratchDatabaseName`, `SCRATCH_DATABASE_PREFIX`
 * + random suffix) and takes no input from argv, env, or the backup file —
 * there is no code path from a caller-supplied value to the database this
 * restores into. `DATABASE_URL` supplies only host/port/user/password (its
 * own database name is read and then discarded, never used).
 *
 * Usage:
 *   node scripts/restore-drill.mjs <backup-file.sql.gz> \
 *     [--library-key=<key>] [--expect-sha256=<hex>] \
 *     [--expect-clips-sha256=<hex>] [--keep-scratch]
 *
 * Every flag is optional: without them the drill proves the schema restores
 * (every table in `REQUIRED_TABLES` exists) and that the Clip store's audio
 * came back as binary, and reports the library/clip digests it found.
 * With `--library-key`/`--expect-sha256` it also proves one library's `data`
 * round-trips byte-identical; with `--expect-clips-sha256` it proves the
 * whole Clip store does. Capture both hashes before backing up (`sha256sum`
 * on the library row; `CLIPS_DIGEST_SQL` below for the clips) and pass them
 * in here after restore — see docs/backup.md.
 *
 * Exits 0 only if every check passes; exits 1 and prints which check failed
 * otherwise. Drops the scratch database on the way out, pass or fail —
 * unless `--keep-scratch` is given, in which case it is left in place (and
 * its name printed) so a single library's row can actually be read out of
 * it afterward. This is not the default: whole-database drills and the
 * ordinary "does the backup restore cleanly" check want the scratch
 * database gone every time, so the safe path (drop) needs no flag. See
 * docs/backup.md ("Restore, step by step") for the single-library recovery
 * procedure this flag exists for.
 *
 * Requires `psql` on PATH (same host as `backup.mjs`'s `pg_dump`) and the
 * `pg` npm package (already a dependency of this repo).
 */
import { spawn } from 'node:child_process'
import { createReadStream } from 'node:fs'
import { createGunzip } from 'node:zlib'
import { createHash, randomBytes } from 'node:crypto'
import { createLogger } from '../server/logger.js'
import { createPool } from '../server/db.js'
import { parsePgUrl, sanitizedUriWithDatabase, uriWithDatabase } from './pg-url.mjs'

export const SCRATCH_DATABASE_PREFIX = 'phrase_drill_restore_drill_'

/** Takes no arguments, deliberately — see the module comment above. */
export function scratchDatabaseName() {
  return `${SCRATCH_DATABASE_PREFIX}${randomBytes(8).toString('hex')}`
}

/**
 * Every table the app's own `init()` calls create (`server/db.js`):
 * `createAuthStore` → `users`/`sessions`, `createLibraryStore` →
 * `libraries`, `createClipStore` → `clips` (T063). A backup missing any one
 * of them is a backup that loses something, so the drill fails rather than
 * reporting a clean restore of a partial database.
 */
export const REQUIRED_TABLES = ['users', 'sessions', 'libraries', 'clips']

/**
 * One digest over the whole Clip store, computed *inside Postgres* so the
 * identical statement can be run against the live database before a backup
 * and against the scratch database after a restore — the pre/post pair the
 * `--expect-clips-sha256` check compares. `encode(bytes,'hex')` is what
 * makes it a statement about the audio's actual bytes rather than about row
 * count or `length()`, and the explicit `ORDER BY` makes it reproducible
 * (`string_agg` over an unordered scan is not). `count` rides along so a
 * digest can never be confused with an empty store.
 */
export const CLIPS_DIGEST_SQL = `
  SELECT
    encode(sha256(coalesce(string_agg(hash || ':' || encode(bytes, 'hex') || ':' || mime, E'\\n' ORDER BY hash), '')::bytea), 'hex') AS digest,
    count(*) AS count
  FROM clips
`

const VALUED_FLAGS = new Set(['--library-key', '--expect-sha256', '--expect-clips-sha256'])
const BOOLEAN_FLAGS = new Set(['--keep-scratch'])

export function parseRestoreArgs(argv) {
  const positional = []
  const flags = {}
  for (const arg of argv) {
    if (arg.startsWith('--')) {
      const eq = arg.indexOf('=')
      const key = eq === -1 ? arg : arg.slice(0, eq)
      if (BOOLEAN_FLAGS.has(key)) {
        if (eq !== -1) throw new Error(`${key} takes no value — pass it bare`)
        flags[key] = true
      } else if (VALUED_FLAGS.has(key)) {
        flags[key] = eq === -1 ? '' : arg.slice(eq + 1)
      } else {
        throw new Error(`unrecognized flag: ${key}`)
      }
    } else {
      positional.push(arg)
    }
  }
  if (positional.length === 0) throw new Error('a backup file is required, e.g. node scripts/restore-drill.mjs ./phrase-drill-....sql.gz')
  return {
    backupFile: positional[0],
    libraryKey: flags['--library-key'] ?? null,
    expectSha256: flags['--expect-sha256'] ?? null,
    expectClipsSha256: flags['--expect-clips-sha256'] ?? null,
    keepScratch: flags['--keep-scratch'] ?? false,
  }
}

function run(command, args, { env, stdinStream } = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { env: env ?? process.env, stdio: [stdinStream ? 'pipe' : 'ignore', 'ignore', 'pipe'] })
    let stderr = ''
    child.stderr.on('data', (c) => {
      stderr += c.toString()
    })
    child.on('error', reject)
    child.on('close', (code) => (code === 0 ? resolve() : reject(new Error(`${command} exited ${code}: ${stderr.trim()}`))))
    if (stdinStream) {
      stdinStream.pipe(child.stdin)
      stdinStream.on('error', reject)
    }
  })
}

async function restoreInto({ databaseUrl, scratchName, backupFile, password }) {
  const scratchUri = sanitizedUriWithDatabase(databaseUrl, scratchName)
  const decompressed = createReadStream(backupFile).pipe(createGunzip())
  await run('psql', [scratchUri, '-v', 'ON_ERROR_STOP=1', '-f', '-'], {
    env: { ...process.env, PGPASSWORD: password },
    stdinStream: decompressed,
  })
}

export async function verify({ pool, libraryKey, expectSha256, expectClipsSha256 }) {
  const checks = []

  const { rows: tableRows } = await pool.query(
    `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name = ANY($1)`,
    [REQUIRED_TABLES],
  )
  const found = new Set(tableRows.map((r) => r.table_name))
  for (const table of REQUIRED_TABLES) {
    checks.push({ name: `table "${table}" exists`, pass: found.has(table) })
  }

  if (found.has('clips')) {
    checks.push(...(await verifyClips({ pool, expectClipsSha256 })))
  }

  if (libraryKey) {
    const { rows } = await pool.query('SELECT data FROM libraries WHERE library_key = $1', [libraryKey])
    const row = rows[0]
    checks.push({ name: `library "${libraryKey}" round-trips`, pass: Boolean(row) })
    if (row) {
      const actualSha256 = createHash('sha256').update(row.data).digest('hex')
      if (expectSha256) {
        checks.push({ name: 'restored data is byte-identical to the pre-backup hash', pass: actualSha256 === expectSha256, detail: actualSha256 })
      } else {
        checks.push({ name: 'restored data sha256 (no --expect-sha256 given to compare against)', pass: true, detail: actualSha256 })
      }
    }
  }

  return checks
}

/**
 * The Clip store's own checks (T063's `clips` table). Two distinct
 * questions, because they fail differently:
 *
 * 1. **Did the audio come back as audio?** `pg` returns a `bytea` column as
 *    a Buffer. A string means the column round-tripped through a text path
 *    somewhere between `pg_dump` and here, and the bytes are no longer the
 *    bytes — a corruption a row count or a `length()` check cannot see.
 * 2. **Is it the same audio?** `CLIPS_DIGEST_SQL` over every row, compared
 *    against the same statement run before the backup. Without
 *    `--expect-clips-sha256` the digest is reported rather than compared —
 *    the same as the library's own hash check, and for the same reason: a
 *    number an operator can capture now and compare later beats silence.
 *
 * A database with no clips yet is not a failure — a fresh install has none,
 * and `count` is printed alongside the digest so an unexpectedly empty store
 * is visible rather than merely digested.
 */
async function verifyClips({ pool, expectClipsSha256 }) {
  const checks = []

  const { rows } = await pool.query('SELECT hash, bytes FROM clips')
  const nonBinary = rows.filter((r) => !Buffer.isBuffer(r.bytes))
  checks.push({
    name: 'clip audio round-trips as binary (bytea, not text)',
    pass: nonBinary.length === 0,
    detail: nonBinary.length === 0 ? `${rows.length} clip(s)` : `${nonBinary.length} clip(s) came back as text, e.g. ${nonBinary[0].hash}`,
  })

  const { rows: digestRows } = await pool.query(CLIPS_DIGEST_SQL)
  const { digest, count } = digestRows[0]
  if (expectClipsSha256) {
    checks.push({ name: 'clip store is byte-identical to the pre-backup clip digest', pass: digest === expectClipsSha256, detail: `${digest} over ${count} clip(s)` })
  } else {
    checks.push({ name: 'clip digest (no --expect-clips-sha256 given to compare against)', pass: true, detail: `${digest} over ${count} clip(s)` })
  }

  return checks
}

export async function main(argv = process.argv.slice(2)) {
  const { backupFile, libraryKey, expectSha256, expectClipsSha256, keepScratch } = parseRestoreArgs(argv)

  const databaseUrl = process.env.DATABASE_URL
  if (!databaseUrl) throw new Error('DATABASE_URL is required (host/port/user/password of the Postgres server to restore into)')

  const { password } = parsePgUrl(databaseUrl)
  const logger = createLogger({ secrets: [password].filter(Boolean) })

  const scratchName = scratchDatabaseName()
  if (!scratchName.startsWith(SCRATCH_DATABASE_PREFIX)) {
    // unreachable given scratchDatabaseName's implementation, but this is
    // exactly the assertion that makes "structurally impossible" true
    // rather than merely likely — refuse rather than trust the format.
    throw new Error('refusing to restore: scratch database name does not carry the expected prefix')
  }

  // in-process `pg` connections keep the password embedded in the URI
  // (uriWithDatabase) — never passed to a child process, so there is no
  // argv-exposure concern the way there is for pg_dump/psql below.
  // `createPool` (the same helper `server/db.js` uses for the app itself)
  // picks up `ssl: { rejectUnauthorized: false }` when `databaseUrl` is
  // Render's external hostname, and no ssl option otherwise — this script
  // is often run off-Render (a laptop, GitHub Actions) against exactly that
  // external hostname, so it needs the same TLS handling the app gets for
  // free on Render's internal network.
  const maintenancePool = createPool(uriWithDatabase(databaseUrl, 'postgres'))

  let pool
  let scratchDropped = true
  try {
    logger.info('restore-drill: creating scratch database', { scratchName })
    await maintenancePool.query(`CREATE DATABASE "${scratchName}"`)

    logger.info('restore-drill: restoring', { backupFile, scratchName })
    await restoreInto({ databaseUrl, scratchName, backupFile, password })

    pool = createPool(uriWithDatabase(databaseUrl, scratchName))
    const checks = await verify({ pool, libraryKey, expectSha256, expectClipsSha256 })

    for (const check of checks) {
      const line = `${check.pass ? 'PASS' : 'FAIL'} — ${check.name}${check.detail ? ` (${check.detail})` : ''}`
      console.log(line)
    }

    const failed = checks.filter((c) => !c.pass)
    if (failed.length > 0) {
      logger.error('restore-drill: failed', { failedChecks: failed.map((c) => c.name) })
      process.exitCode = 1
    } else {
      logger.info('restore-drill: all checks passed', { count: checks.length })
    }
  } catch (err) {
    logger.error('restore-drill: failed', { error: err instanceof Error ? err.message : String(err) })
    process.exitCode = 1
  } finally {
    if (pool) await pool.end().catch(() => {})
    if (keepScratch) {
      scratchDropped = false
      const scratchUri = sanitizedUriWithDatabase(databaseUrl, scratchName)
      // deliberately printed, not just logged: this is the one thing an
      // operator needs to copy-paste next, in an incident, possibly under
      // time pressure — see docs/backup.md "Recovering a single library".
      console.log(`KEPT scratch database — connect with: PGPASSWORD=<same password as DATABASE_URL> psql '${scratchUri}'`)
      console.log(`     scratch database name: ${scratchName}`)
      console.log(`     drop it yourself when done: psql '${sanitizedUriWithDatabase(databaseUrl, 'postgres')}' -c 'DROP DATABASE "${scratchName}" WITH (FORCE)'`)
      logger.info('restore-drill: keeping scratch database (--keep-scratch)', { scratchName })
    } else {
      logger.info('restore-drill: dropping scratch database', { scratchName })
      await maintenancePool.query(`DROP DATABASE IF EXISTS "${scratchName}" WITH (FORCE)`).catch(async () => {
        // WITH (FORCE) needs Postgres 13+; fall back for anything older.
        await maintenancePool.query(`DROP DATABASE IF EXISTS "${scratchName}"`).catch(() => {})
      })
    }
    await maintenancePool.end().catch(() => {})
  }
  return { scratchName, scratchDropped }
}

const isMain = process.argv[1] && import.meta.url === new URL(process.argv[1], 'file:').href
if (isMain) {
  main().catch(() => {
    process.exitCode = 1
  })
}
